# Site settings
title: Zhy Blog
SEOTitle: 张浩烨的博客 | Zhy Blog
header-img: img/home-bg-1.jpg
email: zhyiliyun@gmail.com
description: "这里是 @Zhy 张浩烨 的个人博客，与你一起发现更大的世界。"
keyword: "博客, 个人网站, 互联网,Android,算法，加密"
url: "http://blog.iliyun.net"              # your host, for absolute URL
baseurl: ""                                # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     2652356325
zhihu_username:     zhang-ye-4-9
github_username:    xzwc
#twitter_username:  zhy
facebook_username:  100008378567444
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: iliyun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: b4c28bf04ae8ce2950cc268148993628
# Google Analytics
ga_track_id: 'UA-80640914-1'            # Format: UA-xxxxxx-xx
ga_domain: blog.iliyun.net



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，看看产品。世界那么大，我想去看看。"
sidebar-avatar: /img/avater-zhang.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "ChiChou",
        href: "http://chichou.me/"
    },{
        title: "Hongyang",
        href: "http://blog.csdn.net/lmj623565791"
    },{
        title: "guolin",
        href: "http://blog.csdn.net/guolin_blog"
    },{
        title: "亓斌",
        href: "http://blog.csdn.net/qibin0506"
    }
]
